<a href="https://colab.research.google.com/github/Rajan0110/AILabNewRepo/blob/main/BAM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np

def bipolar_encode(data):
    """Convert binary list to bipolar (-1,1)"""
    return np.array([1 if d == 1 else -1 for d in data])

def bipolar_decode(data):
    """Convert bipolar to binary (0,1)"""
    return np.array([1 if d == 1 else 0 for d in data])

def sgn(x):
    return np.where(x >= 0, 1, -1)

IDs = [
    [0,1,0,1],
    [1,0,1,0],
    [1,1,0,0]
]

Phones = [
    [1,0,1,1],
    [0,1,0,0],
    [1,1,1,0]
]

X = np.array([bipolar_encode(id_) for id_ in IDs])
Y = np.array([bipolar_encode(ph) for ph in Phones])

W = X.T @ Y
print("Weight Matrix W:\n", W)

def recall(input_pattern, W, max_iter=10):
    x = bipolar_encode(input_pattern)
    for i in range(max_iter):
        y_new = sgn(x @ W)
        x_new = sgn(y_new @ W.T)
        if np.array_equal(x, x_new) and np.array_equal(y_new, sgn(x @ W)):
            break
        x, y = x_new, y_new
    return bipolar_decode(x_new), bipolar_decode(y_new)

test_ID = [1,0,1,0]
x_rec, y_rec = recall(test_ID, W)
print(f"\nInput ID (binary): {test_ID}")
print(f"Recalled ID: {x_rec}")
print(f"Recalled Phone: {y_rec}")


Weight Matrix W:
 [[-1  3 -1 -3]
 [ 3 -1  3  1]
 [-3  1 -3 -1]
 [ 1 -3  1  3]]

Input ID (binary): [1, 0, 1, 0]
Recalled ID: [1 0 1 0]
Recalled Phone: [0 1 0 0]
